### ISSUE TITLE
can't create invoice in our live crowdfund, since updating to 1.0.4.1 

### ISSUE THREAD

**Issue by Eskyee** [btcpayserver/btcpayserver#1483]
**Describe the problem/bug**
since updating from the stable branch 8 hours ago
donations are now not being accepted, there is no cap, so this should not happen.
when you hit contribute, the request is made, but the screen is blank. ??? 
and the user doesn't know what has happened , as they can't donate.

the link is here https://btcpayjungle.com/apps/3AhSqQNivB9qzGSoCgMWe9jwWExg/crowdfund

and the last time a donation was received successful was at 4/18/2020 10:15:14 PM
I can see 
OrderId | InvoiceId | Status | Amount in my invoices, so I know something broken in between that.

**Your environment**

Version of BTCPay Server: 1.0.4.1
Deployment method: docker

I wouldn't update during a live campaign, but since a update was pushed to the stable branch
and the fix wast todo with Payjoin etc etc, I made this update as I regarded it as a important update.

**Comment by Eskyee** [comment]
<img width="1329" alt="Screenshot 2020-04-19 at 07 49 46" src="https://user-images.githubusercontent.com/30862925/79681464-609ac780-8212-11ea-8b8f-44909fa70388.png">
 this is the reason I updated, leading to a break in the crowdfund app

**Comment by Eskyee** [comment]
I can see via the invoices page, when clicking checkout, I get to see the checkout window.

**Comment by Kukks** [comment]
You are running an unreleased version( you forked and did not use the tagged version commit)

**Comment by Eskyee** [comment]
I used the stable branch version as I always have done

**Comment by Eskyee** [comment]
and I yes I used a tag 1.0.4.1

**Comment by Eskyee** [comment]
anyway I update now, and see what happens.

**Comment by Eskyee** [comment]
![Screenshot 2020-04-19 at 08 58 42](https://user-images.githubusercontent.com/30862925/79682678-07d02c80-821c-11ea-97db-56660f6df697.png)

So why was a fix needed if im running a unreleased version ????  
I alway use the tagged version commit. never had problems like that in the past. lol

**Comment by pavlenex** [comment]
> So why was a fix needed if im running a unreleased version ????

The "you are running a unreleased tag" was a reply to you implying this has not been tested before release. It's fixed now.

**Comment by Eskyee** [comment]
If I’m pulling front the stable branch! I consider this as released pav ! 
Cheers and yes the problem is now fixed 
From a true or false fix ☝️😂
Back to the grind..

**Comment by Eskyee** [comment]
![Screenshot 2020-04-19 at 09 43 16](https://user-images.githubusercontent.com/30862925/79683477-508ae400-8222-11ea-9325-3a2d1f850523.png)

as you can see above the Stable Branch.

**Comment by Eskyee** [comment]
<img width="1329" alt="Screenshot 2020-04-19 at 09 50 03" src="https://user-images.githubusercontent.com/30862925/79683599-343b7700-8223-11ea-91c7-5cd16999ff9e.png">
 the official release, in case you missed it.

**Comment by Eskyee** [comment]
no stress, but I thought you want to see that.

**Comment by Kukks** [comment]
> 
> 
> I used the stable branch version as I always have done

That's on docker. Since you override the docker image, it's irrelevant. If you created the image from master on this repo, instead of the tagged release commit, you ran an unreleased version.
