### ISSUE TITLE
Pi 4 pulling amd64 docker images.

### ISSUE THREAD

**Issue by Jackster** [btcpayserver/btcpayserver#2429]
Trying to see if I can get BTCpay working on Raspi 4 but the setup config looks to be pulling the amd64 image not the armv7 image?

"ARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm/v7) and no specific platform was requested"

> BTCPay Server docker-compose parameters saved in /root/.env
> 
> Trying to install docker...
> # Executing docker install script, commit: 3d8fe77c2c46c5b7571f94b42793905e5b3e4                                                                                                                                        2e4
> + sh -c apt-get update -qq >/dev/null
> + sh -c DEBIAN_FRONTEND=noninteractive apt-get install -y -qq apt-transport-https ca-certificates curl >/dev/null
> + sh -c curl -fsSL "https://download.docker.com/linux/raspbian/gpg" | apt-key add -qq - >/dev/null
> Warning: apt-key output should not be parsed (stdout is not a terminal)
> + sh -c echo "deb [arch=armhf] https://download.docker.com/linux/raspbian buster stable" > /etc/apt/sources.list.d/docker.list
> + sh -c apt-get update -qq >/dev/null
> + [ -n  ]
> + sh -c apt-get install -y -qq --no-install-recommends docker-ce >/dev/null
> + sh -c docker version
> Client: Docker Engine - Community
>  Version:           20.10.5
>  API version:       1.41
>  Go version:        go1.13.15
>  Git commit:        55c4c88
>  Built:             Tue Mar  2 20:18:46 2021
>  OS/Arch:           linux/arm
>  Context:           default
>  Experimental:      true
> 
> Server: Docker Engine - Community
>  Engine:
>   Version:          20.10.5
>   API version:      1.41 (minimum version 1.12)
>   Go version:       go1.13.15
>   Git commit:       363e9a8
>   Built:            Tue Mar  2 20:16:18 2021
>   OS/Arch:          linux/arm
>   Experimental:     false
>  containerd:
>   Version:          1.4.4
>   GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
>  runc:
>   Version:          1.0.0-rc93
>   GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
>  docker-init:
>   Version:          0.19.0
>   GitCommit:        de40ad0
> If you would like to use Docker as a non-root user, you should now consider
> adding your user to the "docker" group with something like:
> 
>   sudo usermod -aG docker your-user
> 
> Remember that you will have to log out and back in for this to take effect!
> 
> WARNING: Adding a user to the "docker" group will grant the ability to run
>          containers which can be used to obtain root privileges on the
>          docker host.
>          Refer to https://docs.docker.com/engine/security/security/#docker-daemon-attack-surface
>          for more information.
> Trying to install docker-compose by using the btcpayserver/docker-compose (armv7l)
> Unable to find image 'btcpayserver/docker-compose:1.28.5' locally
> 1.28.5: Pulling from btcpayserver/docker-compose
> 61211de2ba72: Pull complete
> 84a2538fa204: Pull complete
> Digest: sha256:6f133d064e5d7be00fb226de8d19aff56a7c23821891092b9b118204b050d35a
> Status: Downloaded newer image for btcpayserver/docker-compose:1.28.5
> WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm/v7) and no specific platform was reque                                                                       sted
> Using default tag: latest
> latest: Pulling from btcpayserver/docker-compose-generator
> 2dd003996c9a: Pull complete
> f775b43aa779: Pull complete
> 3c01276238d4: Pull complete
> f7ec7a013351: Pull complete
> 8f11dab9d3eb: Pull complete
> 5b0e2e893bad: Pull complete
> 5c4c521b1add: Pull complete
> Digest: sha256:ed69f844a6f640cd95d4816af6f054651e7ddbe069a72be0a299c4e1c69c6cfa
> Status: Downloaded newer image for btcpayserver/docker-compose-generator:latest
> docker.io/btcpayserver/docker-compose-generator:latest
> WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm/v7) and no specific platform was reque                                                                       sted
> Crypto: btc
> Lightning: lnd
> ReverseProxy: nginx
> Generating /app/Generated/docker-compose.generated.yml
> Selected fragments:
>         nginx
>         btcpayserver
>         bitcoin
>         bitcoin-lnd
>         opt-more-memory
>         btcpayserver-nginx
>         postgres
>         nbxplorer
>         opt-add-zmq
>         nginx-https
>         opt-add-tor
> Generated /app/Generated/pull-images.sh
> Generated /app/Generated/save-images.sh
> Generated /app/Generated/docker-compose.generated.yml
> 
> Adding btcpayserver.service to systemd
> Setting limited log files in /etc/docker/daemon.json
> BTCPay Server systemd configured in /etc/systemd/system/btcpayserver.service
> 
> Created symlink /etc/systemd/system/multi-user.target.wants/btcpayserver.service → /etc/systemd/system/btcpayserver.service.
> BTCPay Server starting... this can take 5 to 10 minutes...
> BTCPay Server started
> Traceback (most recent call last):
>   File "docker-compose", line 2, in <module>
>   File "/usr/local/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
>   File "compose/cli/main.py", line 13, in <module>
> ModuleNotFoundError: No module named 'docker'
> [3047] Failed to execute script docker-compose
> Traceback (most recent call last):
>   File "docker-compose", line 2, in <module>
>   File "/usr/local/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
>   File "compose/cli/main.py", line 13, in <module>
> ModuleNotFoundError: No module named 'docker'
> [3049] Failed to execute script docker-compose
> Installed bitcoin-cli.sh to /usr/local/bin: Command line for your Bitcoin instance
> Installed bitcoin-lncli.sh to /usr/local/bin: Command line for your Bitcoin LND instance
> Installed btcpay-clean.sh to /usr/local/bin: Command line for deleting old unused docker images
> Installed btcpay-down.sh to /usr/local/bin: Command line for stopping all services related to BTCPay Server
> Installed btcpay-restart.sh to /usr/local/bin: Command line for restarting all services related to BTCPay Server
> Installed btcpay-setup.sh to /usr/local/bin: Command line for restarting all services related to BTCPay Server
> Installed btcpay-up.sh to /usr/local/bin: Command line for starting all services related to BTCPay Server
> Installed btcpay-admin.sh to /usr/local/bin: Command line for some administrative operation in BTCPay Server
> Installed btcpay-update.sh to /usr/local/bin: Command line for updating your BTCPay Server to the latest commit of this repository
> Installed changedomain.sh to /usr/local/bin: Command line for changing the external domain of your BTCPay Server
> root@raspberrypi:~/btcpayserver-docker#

Raspberry Pi 4 with the Rasp OS Lite operating system. Fully updated. Using the guide on the official website.

**Comment by dennisreimann** [comment]
@NicolasDorier this looks like what I also brought up [here](https://chat.btcpayserver.org/btcpayserver/pl/uauc6fu56fgoujppdeadqnkq3h).

**Comment by Jackster** [comment]
> @NicolasDorier this looks like what I also brought up [here](https://chat.btcpayserver.org/btcpayserver/pl/uauc6fu56fgoujppdeadqnkq3h).

How did you fix this? I'm not very good with Docker.

**Comment by NicolasDorier** [comment]
Checking that, I recently updated docker-compose so that may be why...

**Comment by NicolasDorier** [comment]
Trying to replicate the issue, found out the docker-compose image does not work properly even on arm64. Looking into it.

**Comment by NicolasDorier** [comment]
@Jackster this issue should be solved, you need to `btcpay-update.sh` one more time. Sorry for inconvenience.

**Comment by NicolasDorier** [comment]
@dennisreimann the warning is strange. I can't explain the warning, but it works. I guess the warning is a bug of specifc version of docker and not critical. This is different from this bug though.

**Comment by NicolasDorier** [comment]
You might need to run `rm /usr/local/bin/docker-compose` before

**Comment by Jackster** [comment]
Still having the same issue.

`
root@raspberrypi:~/btcpayserver-docker# btcpay-update.sh
Already up to date.
Using default tag: latest
latest: Pulling from btcpayserver/docker-compose-generator
Digest: sha256:603ab55cd906cff7176acf800fbe8b6e900a5c12af94e2948ea9bbaa7264b58a
Status: Image is up to date for btcpayserver/docker-compose-generator:latest
docker.io/btcpayserver/docker-compose-generator:latest
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm/v7) and no specific platform was requested
`

Maybe just me? xD

**Comment by dennisreimann** [comment]
@Jackster I finally figured out what the problem was and got it fixed: You are running the 32bit OS version and the image only works with the 64bit one.

Most likely you'll be able to easily switch to the 64bit OS, by doing the following:

1. Verify you are running the 32bit version: `uname -a` should give you output with 
    - 32bit: "armv7l"
    - 64bit: "aarch64"
2. If it's the 32 version upgrade everything: `sudo apt update && sudo apt upgrade`
3. See if the 64 kernel is present: `sudo ls /boot/kernel8.img`
4. If so, edit the boot config: `sudo nano /boot/config.txt`
5. Add this line at the end: `arm_64bit=1`
6. Reboot: `sudo reboot`
7. Wait a few seconds, log back in and verify it booted correctly with the command from step 1
