### ISSUE TITLE
Invoices not getting marked as confirmed (stuck in new) and not running CallBack sometimes

### ISSUE THREAD

**Issue by iamvinny** [btcpayserver/btcpayserver#31]
I had a customer who paid an invoice, the callback was supposed to be sent to my site and the invoice marked as confirmed, I checked on blockchain.info and I could see the payment there, however on BTCPay server it wasn't confirmed nor the callback was sent to my server.

My store's setting is set to consider the invoice confirmed when the payment is unconfirmed.

![Store Setting](https://i.imgur.com/S6coPOi.png)

Here is the invoice

![Invoice Screenshot](https://i.imgur.com/qgVsRag.png)
It's been more than 60 minutes and still stuck in "new".

On blockchain the payment has already 6 confirmations.

https://blockchain.info/address/39Ren1X75iViTtTLCa3nLMrU1oHB9a98Xz

**Comment by NicolasDorier** [comment]
hey, can you try again with latest version ? I fixed lot's of bug yestersday.

**Comment by NicolasDorier** [comment]
Try the BTCPayServer with 1.0.0.76 and NBXPlorer 1.0.0.63 (Deployed on https://test-btc-ltc.forkbitpay.ninja/)

**Comment by NicolasDorier** [comment]
can you try on https://test2-btc-ltc.forkbitpay.ninja/ ? I need to wait one week before  https://test-btc-ltc.forkbitpay.ninja/ can get a certificate :(

**Comment by iamvinny** [comment]
It's still not working properly, I have created some invoices on the link you sent me, but none of them expired after 15 minutes.
![invoices Screenshot](https://i.imgur.com/yZ0JnPz.png)

When I open one of them, it bugs after clicking in "Copy" and then "Scan" again.
![Invoice Bug Screenshot](https://i.imgur.com/yZ0JnPz.png)

It seems like they only update to "expired" when I restart the server.

**Comment by NicolasDorier** [comment]
thanks, trying to reproduce this.

**Comment by iamvinny** [comment]
Ok, thanks, keep me updated, this is the only thing preventing me to use BTCPay on my site.

**Comment by NicolasDorier** [comment]
ok there was indeed a bug, you should update to nbxplorer:1.0.1.4  and btcpayserver:1.0.1.3 I updated my server can you check if you can replicate the issue and close if this is solved ?

**Comment by iamvinny** [comment]
The same problem happened again, I set the expire time to 1 minute, and created some invoices, only one of them expired.

![Invoice Bug Screenshot](https://i.imgur.com/3CZrk4P.png)

**Comment by iamvinny** [comment]
It's still not working on v1.0.1.4, they won't expire :(

**Comment by NicolasDorier** [comment]
yeah I closed by mistake

**Comment by NicolasDorier** [comment]
took me a while, it was happening only on the tests servers :(   1.0.1.7 should fix that, testing now.

**Comment by NicolasDorier** [comment]
OK fixed in 1.0.1.7

**Comment by NicolasDorier** [comment]
I let you verify and close it. It is good now.

**Comment by iamvinny** [comment]
Thanks a lot, it's working perfectly now! 😄

**Comment by Eskyee** [comment]
👍
