### ISSUE TITLE
[Bug]: When using a proxy it is still possible to see the original BTCPay Server instance URL

### ISSUE THREAD

**Issue by ilearnio** [btcpayserver/btcpayserver#4461]
### What is your BTCPay version?

BTCPay Server v1.6.12.0

### How did you deploy BTCPay Server?

LunaNode (followed official instructions for setting it up)

### What happened?

I just set up a nginx proxy that would allow me to hide the real IP of the BTCPay Server, for security reasons. I was surprised that BTCPay Server is designed to be friendly with such proxying out of the box. However it is still possible to find the original BTCPay Server instance URL in the two buttons on that are displayed on success page, which makes the entire proxy setup useless. See screenshot:

![image](https://user-images.githubusercontent.com/14331216/208769488-225a7d7a-512d-4772-a434-97a94d05f0fb.png)

### How did you encounter this bug?

I paid for the order and on the success page there are two buttons, both lead to the original server

### What browser do you use?

Chrome

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

**Comment by dennisreimann** [comment]
What is the domain value on the Server Settings > Maintenance page? That's the main domain that gets used.

The "Return to Store" button points to the "Store Website" configured in the Store Settings > General.

**Comment by ilearnio** [comment]
@dennisreimann It is set to the original server's URL which I would like to hide. I just tried to change it to the proxy URL but getting this error 

```
Invalid host (... is not pointing to this BTCPay instance)
```

However the URL works well when opening it in a Chrome tab and shows the BTCPay server login page.


Here's the nginx file on the server that is used as a proxy, if it helps:

```nginx
server {
    if ($host = jackpot6000-btcpay.mydomain.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


  listen 80;
  server_name jackpot6000-btcpay.mydomain.com;
  return 301 https://$server_name$request_uri;
}

server {
  listen 443 ssl;
  server_name jackpot6000-btcpay.mydomain.com;

  access_log /var/log/nginx/jackpot6000-btcpay.mydomain.com.access.log;
  error_log /var/log/nginx/jackpot6000-btcpay.mydomain.com.error.log info;

  # doesn't work with self-signed certs
  ssl_stapling on;
  ssl_stapling_verify on;
  
  ssl_session_timeout 1d;
  ssl_session_cache shared:SSL:10m;
  ssl_session_tickets off;

  resolver 8.8.8.8 8.8.4.4 valid=300s;
  resolver_timeout 30s;

  add_header Strict-Transport-Security "max-age=63072000" always;
  # add_header Content-Security-Policy "frame-ancestors 'self','http://localhost:3000','https://jackpot6000.loc'";
  add_header X-Content-Type-Options nosniff;

location / {
  #location ~ ^/(i/|checkout/|locales/|apps/|bundles/|main/|vendor/|img/|imlegacy/|js/|fonts|favicon.ico) {
    proxy_pass https://btcpay379576.lndyn.com;
    proxy_http_version 1.1;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Upgrade $http_upgrade;
  }

    ssl_certificate /etc/letsencrypt/live/jackpot6000-btcpay.mydomain.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/jackpot6000-btcpay.mydomain.com/privkey.pem; # managed by Certbot
}
```

**Comment by dennisreimann** [comment]
I think [this FAQ item in the docs](https://docs.btcpayserver.org/FAQ/Deployment/#can-i-use-an-existing-nginx-server-as-a-reverse-proxy-with-ssl-termination) contains some valuable information for your case: E.g. the `proxy_set_header Host $http_host;` directive seems to be missing.

**Comment by ilearnio** [comment]
@dennisreimann I just tried to copy the contents of that nginx config, it still didn't help. However had problems defining the `proxy_set_header Host $http_host;`, for some reason the nginx was responding with 503, and I guess that error was comming from the BTCPay Server's nginx, because I can see that error in logs of nginx docker image (unfortunately these nginx logs doesn't provide any details on why it happens, it only shows that the request was resolved with 503 status code). It works though when I type the original BTCPAy server URL instead of "$http_host" so I'm not sure already what value it expects. Also tried to enter the host of the proxy server without using a variable, but and also got 503.

> The "Return to Store" button points to the "Store Website" configured in the Store Settings > General.

I updated the "Store Website" as you suggested however it didn't help, the button still points to the original domain.

**Comment by dennisreimann** [comment]
There are [multiple reasons for the 503](https://docs.btcpayserver.org/FAQ/Deployment/#i-get-503-service-temporarily-unavailable-nginx), I assume it might be related to doing SSL termination on the frontend proxy and passing on the HTTPS scheme — see "Cause 3" for a potential fix. 

Though this doesn't directly fit with what you are saying about entering the host directly instead of using the variable — you might also wanna try `proxy_set_header Host $host;`.

> I updated the "Store Website" as you suggested however it didn't help, the button still points to the original domain.

Note that the URL gets applied on invoice creation, so this won't work for invoices that existed before changing the Store Website.

**Comment by ilearnio** [comment]
> Note that the URL gets applied on invoice creation, so this won't work for invoices that existed before changing the Store Website.

@dennisreimann I just tested it once again on a completely new order and the buttons still give the original URL, not the one I entered in Settings -> General

**Comment by NicolasDorier** [comment]
it's not a bug, you need to add

```
		proxy_set_header Host $http_host;
		proxy_set_header X-Forwarded-Proto $scheme;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
```
This is documented on https://docs.btcpayserver.org/FAQ/Deployment/#can-i-use-an-existing-nginx-server-as-a-reverse-proxy-with-ssl-termination

You forgot `proxy_set_header Host $http_host;`

Be sure the `BTCPAY_HOST` is set properly to `jackpot6000-btcpay.mydomain.com`, and that the https fragment is removed. (else btcpay nginx will attempt to setup https rather than HTTP)

```
export BTCPAY_HOST="jackpot6000-btcpay.mydomain.com"
export BTCPAYGEN_EXCLUDE_FRAGMENTS="nginx-https"
. btcpay-setup.sh -i
```
