### ISSUE TITLE
[Bug]: POST /api/v1/invoices fails on "duplicate key value violates unique constraint PK_AddressInvoices"

### ISSUE THREAD

**Issue by iBobik** [btcpayserver/btcpayserver#6628]
### What is your BTCPay version?

v2.0.6 and v2.0.7

### How did you deploy BTCPay Server?

Docker

### What happened?

Invoice creation by Pay Button endpoint fails.

### How did you encounter this bug?

1. Trying to create invoice by /api/v1/invoices (public API)

### Relevant log output

```shell
nginx                        | pay.berubitcoin.cz 172.17.0.1 - - [14/Mar/2025:14:48:14 +0000] "POST /api/v1/invoices HTTP/1.1" 500 0 "https://form.simpleshop.cz/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.3 Safari/605.1.15"
btcpayserver_1               | fail: Microsoft.EntityFrameworkCore.Update: An exception occurred in the database while saving changes for context type 'BTCPayServer.Data.ApplicationDbContext'.
postgres_1                   | 2025-03-14 14:48:14.864 UTC [371] ERROR:  duplicate key value violates unique constraint "PK_AddressInvoices"
postgres_1                   | 2025-03-14 14:48:14.864 UTC [371] DETAIL:  Key ("Address", "PaymentMethodId")=(dd872689eb1b68367c3c28deb91e1091e45cab18, BTC-CHAIN) already exists.
postgres_1                   | 2025-03-14 14:48:14.864 UTC [371] STATEMENT:  INSERT INTO "AddressInvoices" ("Address", "PaymentMethodId", "InvoiceDataId")
postgres_1                   | 	VALUES ($1, $2, $3)
btcpayserver_1               |       Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
btcpayserver_1               |        ---> Npgsql.PostgresException (0x80004005): 23505: duplicate key value violates unique constraint "PK_AddressInvoices"
btcpayserver_1               |       
btcpayserver_1               |       DETAIL: Detail redacted as it may contain sensitive data. Specify 'Include Error Detail' in the connection string to include this information.
btcpayserver_1               |          at Npgsql.Internal.NpgsqlConnector.ReadMessageLong(Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
btcpayserver_1               |          at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
btcpayserver_1               |          at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
btcpayserver_1               |          at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
btcpayserver_1               |          at Npgsql.EntityFrameworkCore.PostgreSQL.Update.Internal.NpgsqlModificationCommandBatch.Consume(RelationalDataReader reader, Boolean async, CancellationToken cancellationToken)
btcpayserver_1               |         Exception data:
btcpayserver_1               |           Severity: ERROR
btcpayserver_1               |           SqlState: 23505
btcpayserver_1               |           MessageText: duplicate key value violates unique constraint "PK_AddressInvoices"
btcpayserver_1               |           Detail: Detail redacted as it may contain sensitive data. Specify 'Include Error Detail' in the connection string to include this information.
btcpayserver_1               |           SchemaName: public
btcpayserver_1               |           TableName: AddressInvoices
btcpayserver_1               |           ConstraintName: PK_AddressInvoices
btcpayserver_1               |           File: nbtinsert.c
btcpayserver_1               |           Line: 649
btcpayserver_1               |           Routine: _bt_check_unique
btcpayserver_1               |          --- End of inner exception stack trace ---
btcpayserver_1               |          at Npgsql.EntityFrameworkCore.PostgreSQL.Update.Internal.NpgsqlModificationCommandBatch.Consume(RelationalDataReader reader, Boolean async, CancellationToken cancellationToken)
btcpayserver_1               |          at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
btcpayserver_1               |          at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
btcpayserver_1               |          at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
btcpayserver_1               |          at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
btcpayserver_1               |          at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
btcpayserver_1               |          at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
btcpayserver_1               |          at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(StateManager stateManager, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
btcpayserver_1               |          at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.<>c__DisplayClass30_0`2.<<ExecuteAsync>b__0>d.MoveNext()
btcpayserver_1               |       --- End of stack trace from previous location ---
btcpayserver_1               |          at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementationAsync[TState,TResult](Func`4 operation, Func`4 verifySucceeded, TState state, CancellationToken cancellationToken)
btcpayserver_1               |          at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementationAsync[TState,TResult](Func`4 operation, Func`4 verifySucceeded, TState state, CancellationToken cancellationToken)
btcpayserver_1               |          at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
btcpayserver_1               |          at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
btcpayserver_1               | Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
btcpayserver_1               |  ---> Npgsql.PostgresException (0x80004005): 23505: duplicate key value violates unique constraint "PK_AddressInvoices"
btcpayserver_1               | 
btcpayserver_1               | DETAIL: Detail redacted as it may contain sensitive data. Specify 'Include Error Detail' in the connection string to include this information.
btcpayserver_1               |    at Npgsql.Internal.NpgsqlConnector.ReadMessageLong(Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
btcpayserver_1               |    at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
btcpayserver_1               |    at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
btcpayserver_1               |    at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
btcpayserver_1               |    at Npgsql.EntityFrameworkCore.PostgreSQL.Update.Internal.NpgsqlModificationCommandBatch.Consume(RelationalDataReader reader, Boolean async, CancellationToken cancellationToken)
btcpayserver_1               |   Exception data:
btcpayserver_1               |     Severity: ERROR
btcpayserver_1               |     SqlState: 23505
```

### What browser do you use?

Safari, Curl

### Are you sure this is a bug report?

- [x] I confirm this is a bug report

**Comment by iBobik** [comment]
I experimented with different requests there and it made difference based on the price:
- If price was 5 CZK and less it pass
- If price was 6 CZK and more it fails

I have no limits for methods in Checkout Experience store settings.

**Comment by iBobik** [comment]
I tried to remove on-chain wallet from the store (xpub to Trezor) and it started working for any price (LN only). Then I configured on-chain wallet back with the same xpub and it keeps working.

So it seems like there was some inconsistency in DB which was fixed by this operation.

But I think it is worth attention so thinks like this will not happen again.

**Comment by Orcinus21** [comment]
I encountered the same problem when on-chain and LN is active in the POS application. When I disable the on-chain wallet, I can generate invoices again. The problem was not solved after I reactivated the on-chain wallet or removed/added it.

I run the 2.1.1 version.

**Comment by NicolasDorier** [comment]
How to reproduce the issue:
* Setup BTCPay
* Generate invoice
* Delete NBXPlorer database
* Generate invoice

Since NBXplorer is responsible to generate new addresses, wiping the database will create addresses which already map to invoices in BTCPay Server.

There is no good way to solve this solution. This solution goes away by itself by trying to generate many invoices, triggering every time the exception. After a while, NBXplorer catch up to addresses BTCPay never saw and it works again.

Reconfiguring the xpub shouldn't have any impact to it. In @iBobik case, it probably happened as NBXplorer caught up the latest addresses.

I don't have explanation about why in your case, NBXplorer started generating old addresses. It may have been data corruption or some crash reboot. I can't really reproduce this.
